#FN-39 feat: view and update user profile
atlp-rwanda/ecommerce-app-cogito-fe pull request #13
Opened 2023-06-13 09:17 UTC by EvelyneUmubyeyi

# PR Description
In this PR I created pages for viewing and updating user profiles.

## Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style

- [ ] Create a view profile page
- [ ] Create update profile page

## Description of tasks that were expected to be completed and that are not yet completed

- [ ] None

## How this may be tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

1. run `yarn i` to install all required dependencies
2. run `yarn run dev`
3. Go to profile page /profile and update profile page /updateProfile 

## Screenshots (If appropriate/applicable)

Provide screenshots related to your PR in case it's appropriate and applicable

## Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My code generates no warnings
- [ ] There are no vulnerabilities

2023-06-29 13:40 UTC, Charlesntwari approved these changes

2023-06-29 13:46 UTC, Charlesntwari approved these changes

2023-06-29 14:13 UTC, Illustre13 requested changes

2023-06-29 14:13 UTC, Illustre13 commented on src/utils/api.tsx
> +dotenv.config()
Remove the dotenv import here

2023-06-29 14:25 UTC, Illustre13 commented on src/utils/api.tsx
> +dotenv.config()
Okay

2023-06-29 14:26 UTC, Illustre13 approved these changes

2023-06-29 14:39 UTC, Honore123 approved these changes

2023-06-29 14:39 UTC, Honore123 commented on vite.config.ts
Add environmentPlugin so that we can use process in util api.tsx

2023-06-30 07:38 UTC, dushimeemma requested changes
Please show the profile and edit profile pages if and if the user is authenticated.

2023-07-05 14:35 UTC, dushimeemma approved these changes

2023-07-05 14:35 UTC, merged