#FN-42 feat: Seller create/add items
atlp-rwanda/ecommerce-app-cogito-fe pull request #14
Opened 2023-06-13 10:47 UTC by Lydie260

# PR Description
As a Seller
I should be able to add/create items for sale
This page should only be accessible to sellers, i.e authenticated
Such that the stock can be seen by any requesting client
Handle all responses and errors from the backend.

Please include a brief description of the pull request you want to raise.

## Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style

- [ ] Add product to the seller's collection

## Description of tasks that were expected to be completed and that are not yet completed

- [ ] Create .....
- [ ] Add .....
- [ ] ......

## How this may be tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

1. run `yarn i` to install all required dependencies
2. run `yarn run dev`
3. step 3
4. step 4...

## Screenshots (If appropriate/applicable)

Provide screenshots related to your PR in case it's appropriate and applicable

## Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My code generates no warnings
- [ ] There are no vulnerabilities

2023-06-29 14:18 UTC, Honore123 reviewed
Allow vendors to add at least 4 images per product

2023-07-10 13:08 UTC, Honore123 approved these changes

2023-07-10 13:09 UTC, Charlesntwari approved these changes

2023-07-11 07:01 UTC, dushimeemma requested changes
- Why are you using `npm` while others are using `yarn`
- Enable to test your PR, what are the steps to follow?

2023-07-11 11:38 UTC, Lydie260 commented
> * Why are you using `npm` while others are using `yarn`
> * Enable to test your PR, what are the steps to follow?
Done with correction

2023-07-12 07:01 UTC, dushimeemma requested changes

2023-07-12 07:01 UTC, dushimeemma commented on src/App.tsx
> +          {/* <NavBar /> */}
Why did you comment on this line of code?

2023-07-12 07:01 UTC, dushimeemma commented on src/App.tsx
> +          {/* <Footer /> */}
Why did you comment this line of code?

2023-07-12 09:17 UTC, Lydie260 commented on src/App.tsx
> +          {/* <NavBar /> */}
I did it because for dashboard it looks weird to have dashboard and footer

2023-07-12 09:18 UTC, Lydie260 commented on src/App.tsx
> +          {/* <Footer /> */}
I did it because for dashboard it looks weird to have dashboard and footer

2023-07-13 08:35 UTC, dushimeemma approved these changes

2023-07-13 08:35 UTC, merged