FN FT-#49: User should sign up
atlp-rwanda/ecommerce-app-cogito-fe pull request #17
Opened 2023-06-14 08:55 UTC by Niyobuzima

# PR Description

To be able to use the application and access authenticated routes, Users should be able to Signup and or Register using Sign up forms on the signup route.
Users cannot access the application without logging in without providing an email and password combination
After a user successfully registers, when they click the verification link in the email it should redirect to the deployed frontend login page

## Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style

- [x] User successfully signs up/registers.
- [x] User passes appropriate signup parameters
- [x] The user should receive verification link on email upon successful registration

## Description of tasks that were expected to be completed and that are not yet completed

- [x] None

## How this may be tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

1. run `yarn i` to install all required dependencies
2. run `yarn run dev`
3. step 3
4. step 4...

## Screenshots (If appropriate/applicable)

Provide screenshots related to your PR in case it's appropriate and applicable

## Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My code generates no warnings
- [ ] There are no vulnerabilities

2023-06-19 07:31 UTC, Illustre13 approved these changes
Well Done bro!!

2023-06-19 07:37 UTC, Illustre13 reviewed
Well Done bro! 
Kindly squash your commits to 1.

2023-06-23 11:25 UTC, Honore123 reviewed
add navbar and footer on your page, and change the background color to blue sky!

2023-06-23 11:25 UTC, Honore123 commented on src/pages/register.tsx
> +        <p className="text-center">Create Your Account In Seconds</p>
Change text color to black

2023-06-23 11:25 UTC, Honore123 commented on src/pages/register.tsx
> +        <h3 className='text-center font-bold'>SIGN UP</h3>
Make SignUp font size a little bit bigger

2023-06-23 11:57 UTC, Illustre13 approved these changes

2023-06-23 12:40 UTC, EvelyneUmubyeyi approved these changes

2023-06-26 13:29 UTC, Honore123 approved these changes

2023-06-26 18:35 UTC, dushimeemma requested changes
I am enable to signup on my end @Niyobuzima

2023-06-27 13:57 UTC, dushimeemma approved these changes

2023-06-27 13:57 UTC, merged