#FN-47 feat: prompt update password
atlp-rwanda/ecommerce-app-cogito-fe pull request #20
Opened 2023-06-15 13:47 UTC by Charlesntwari

Trello link: https://trello.com/c/wYKc7NEj/47-users-should-be-presented-with-an-interface-that-prompts-them-to-change-their-passwords-every-x-amount-of-time

# PR Description

User should be prompted to change their passwords every x amount of time
since the time it was either manually updated.

## Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style

- [x] direct to update password
- [x] update password

## Description of tasks that were expected to be completed and that are not yet completed

- [x] None

## How this may be tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

1. run `yarn i` to install all required dependencies
2. run `yarn run dev`
3. log in and update password

## Screenshots (If appropriate/applicable)

Provide screenshots related to your PR in case it's appropriate and applicable

## Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My code generates no warnings
- [ ] There are no vulnerabilities

2023-06-26 15:52 UTC, kunda4 approved these changes
Well done

2023-06-27 14:57 UTC, Honore123 approved these changes

2023-06-28 07:33 UTC, Niyobuzima requested changes
add footer and header

2023-06-28 13:05 UTC, Niyobuzima approved these changes

2023-06-29 05:54 UTC, dushimeemma requested changes
Would you mind removing unnecessary components on the home page?

2023-06-29 07:08 UTC, dushimeemma approved these changes

2023-06-29 07:09 UTC, merged