#FN-144 chore: create top navigation bar and footer
atlp-rwanda/ecommerce-app-cogito-fe pull request #21
Opened 2023-06-20 08:19 UTC by EvelyneUmubyeyi

# PR Description
In this PR I created a top nav bar and footer to be used in the web app.

## Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style

- [x] create the top navigation bar of the web app
- [x] create the footer of the web app

## Description of tasks that were expected to be completed and that are not yet completed

- [x] None

## How this may be tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

1. run `yarn i` to install all required dependencies
2. run `yarn run dev`

## Screenshots (If appropriate/applicable)

Provide screenshots related to your PR in case it's appropriate and applicable

## Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My code generates no warnings
- [x] There are no vulnerabilities

2023-06-20 16:50 UTC, dushimeemma requested changes
Would you mind safely deleting the Greet component and Greet test files?

2023-06-20 16:50 UTC, dushimeemma commented on src/components/Nav/navBar.tsx
> +        <div className="border-[1px] border-[#9C9EBA] text-[#9C9EBA] xl:w-[40%] md:w-[30%] py-1.5 px-3 lg:px-4 md:mr-2 rounded-3xl flex items-center justify-between custom-md:w-[30%]">
I am wondering the reason why this is not a search field!?

2023-06-20 16:55 UTC, Charlesntwari approved these changes

2023-06-21 10:04 UTC, dushimeemma approved these changes
Good job 🥇

2023-06-21 10:10 UTC, Honore123 approved these changes

2023-06-21 10:10 UTC, Honore123 commented on .storybook/main.ts
Delete comments

2023-06-21 10:11 UTC, merged