#FN-33: User should be able to Chat
atlp-rwanda/ecommerce-app-cogito-fe pull request #32
Opened 2023-07-14 09:10 UTC by Niyobuzima

# PR Description
Trello: https://trello.com/c/xglKKsHz
Having travellers interacting with each other on the platform adds value to it as it allows them to asks questions about places, offer recommendations, guidance etc...

## Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style

- [ ] User should open the chat tab
- [ ] User should see past messages
- [ ] User should be able to send messages in public chat

## Description of tasks that were expected to be completed and that are not yet completed

- [ ] none

## How this may be tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

1. run `yarn i` to install all required dependencies
2. run `yarn run dev`

## Screenshots (If appropriate/applicable)

Provide screenshots related to your PR in case it's appropriate and applicable

## Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My code generates no warnings
- [ ] There are no vulnerabilities

2023-07-16 14:15 UTC, Illustre13 commented on src/redux/store/store.tsx
> -    serializableCheck: false,
You can add this back for handling the redux serialization data parsing !!

2023-07-16 14:17 UTC, Illustre13 requested changes
You can add back for handling the redux serialization data parsing !!

2023-07-16 14:17 UTC, Illustre13 commented on src/redux/store/store.tsx
> -    serializableCheck: false,
You can add this back for handling the redux serialization data parsing !!

2023-07-16 15:17 UTC, Illustre13 approved these changes

2023-07-16 16:14 UTC, Honore123 approved these changes

2023-07-17 10:26 UTC, EvelyneUmubyeyi approved these changes

2023-07-17 11:05 UTC, dushimeemma reviewed
While do you request me to enter my name when I am authenticated @Niyobuzima?

2023-07-18 08:52 UTC, dushimeemma approved these changes

2023-07-18 08:52 UTC, merged